Trezanik MemMgr (C++): Allocator Class Reference
Allocator Class Reference
#include <Allocator.h>
Public Member Functions
~Allocator ()
void OutputMemoryInfo ()
void * TrackedAlloc (const uint32_t num_bytes, const char *file, const char *function, const uint32_t line, const Object *owner=nullptr)
void TrackedFree (void *memory)
void * TrackedRealloc (void *memory_block, const uint32_t num_bytes, const char *file, const char *function, const uint32_t line, const Object *owner=nullptr)
Private Member Functions
Allocator operator= (Allocator const &)
Allocator (Allocator const &)
Allocator ()
E_MEMORY_ERROR CheckBlock (memblock_header *memory_block) const
bool ValidateMemory (void *memory) const
Private Attributes
uint32_t _allocs
uint32_t _frees
uint32_t _current_allocated
uint32_t _total_allocated
std::recursive_mutex _mutex
std::vector< memblock_header * > _memblocks
Friends
class Runtime
Detailed Description
Resides within the application runtime and tracks all memory allocations and frees, ensuring data is not corrupt or the memory leaked.
This overrides all new/delete calls so they will NOT be usable, ensuring the correct functions are always called for the application. As system headers should always be included before this one, it will not stop normal API functions from working - if you do have a problem, check your inclusion order!
malloc/free and associates are not overriden, enabling their usage in certain special cases where using this class would be inappropriate or infeasible - such as allocating for this class in the first place.
Definition at line 144 of file Allocator.h.
Constructor & Destructor Documentation
Allocator::Allocator (Allocator const &) private
Allocator::Allocator () private
Definition at line 56 of file Allocator.cc.
References _memblocks.
                      :
         _allocs(0), _frees(0), _current_allocated(0), _total_allocated(0)
 {
         /* reserve 100 internal allocations. Will breach, but should cause the
          * expansions to be 200, 400, 800, etc. */
         _memblocks.reserve(100);
 }
Allocator::~Allocator ()
Definition at line 66 of file Allocator.cc.
References _memblocks, MEM_LEAK_LOG_NAME, and OutputMemoryInfo().
 {
         if ( !_memblocks.empty() )
         {
                 printf("Memory Leak Detected\n\nCheck '%s' for details\n",
                        MEM_LEAK_LOG_NAME);
         }
         OutputMemoryInfo();
 }
Member Function Documentation
E_MEMORY_ERROR Allocator::CheckBlock (memblock_header * memory_block) const private
Checks a block of memory, ensuring both the header and footer are not corrupt, and the rest of the block matches the original requestors specifications.
Define DISABLE_MEMORY_CHECK_TO_STDOUT to prevent stage-by-stage output of the checking process.
Parameters
[in] memory_block The block of memory to check
Return values
E_MEMORY_ERROR The relevant memory error code as to the block status; should hopefully always be EC_NoError
Definition at line 80 of file Allocator.cc.
References EC_CorruptFooter, EC_CorruptHeader, EC_NoError, EC_NoMemoryBlock, EC_SizeMismatch, memblock_header::file, memblock_header::footer, memblock_header::line, memblock_footer::magic, memblock_header::magic, mem_footer_magic, mem_header_magic, memblock_header::real_size, and memblock_header::requested_size.
Referenced by OutputMemoryInfo(), and ValidateMemory().
 {
         uint32_t        block_size = 0;
         if ( memory_block == nullptr )
                 goto null_block;
 #if !defined(DISABLE_MEMORY_CHECK_TO_STDOUT)
         printf("\tChecking Memory Block %p..\n", memory_block);
         printf("\t\tGlobal Header magic number is %lu bytes in size :: %#x\n", sizeof(mem_header_magic), mem_header_magic);
         printf("\t\tGlobal Footer magic number is %lu bytes in size :: %#x\n", sizeof(mem_footer_magic), mem_footer_magic);
 #endif
         if ( memcmp(&memory_block->magic,
                 &mem_header_magic,
                 sizeof(mem_header_magic)) != 0 )
         {
                 /* memory_block magic number has been modified; block contents
                  * are unstable */
                 goto corrupt_header;
         }
 #if !defined(DISABLE_MEMORY_CHECK_TO_STDOUT)
         printf("\t\tHas a valid header (%lu bytes, %#x)...\n",
                 sizeof(memory_block->magic), memory_block->magic);
         printf("\t\tHeader Info:: %u (%u requested) bytes, line %u in %s\n",
                 memory_block->real_size, memory_block->requested_size,
                 memory_block->line, memory_block->file);
 #endif
         if ( memory_block->footer == nullptr ||
                 memcmp(&memory_block->footer->magic, &mem_footer_magic, sizeof(mem_footer_magic)) != 0 )
         {
                 /* memory_block footer magic has been modified - as the header
                  * is not corrupt, we can retrieve the allocation info safely */
                 goto corrupt_footer;
         }
 #if !defined(DISABLE_MEMORY_CHECK_TO_STDOUT)
         printf("\t\tHas a valid footer (%lu bytes, %#x)...\n",
                 sizeof(memory_block->footer->magic),
                 memory_block->footer->magic);
 #endif
         // calculate the size requested by removing the header + footer
         block_size = ((uint8_t*)memory_block->footer) - ((uint8_t*)memory_block + sizeof(memblock_header));
 #if !defined(DISABLE_MEMORY_CHECK_TO_STDOUT)
         printf("\t\tCalculated block_size is %u bytes\n", block_size);
 #endif
         if ( memory_block->requested_size != block_size )
         {
                 /* The size stored by the memory_block header is different from
                  * that calculated (remember we've already validated the magic
                  * numbers) */
                 goto invalid_size;
         }
 #if !defined(DISABLE_MEMORY_CHECK_TO_STDOUT)
         printf("\t\tHas a valid app_mem size (%u bytes)\n\t\tValidated!\n",
                block_size);
 #endif
         // memory_block is as expected
         return E_MEMORY_ERROR::EC_NoError;
 null_block:
         // Optional: Raise error
         return E_MEMORY_ERROR::EC_NoMemoryBlock;
 corrupt_header:
         // Optional: Raise error
         return E_MEMORY_ERROR::EC_CorruptHeader;
 corrupt_footer:
         // Optional: Raise error
         return E_MEMORY_ERROR::EC_CorruptFooter;
 invalid_size:
         // Optional: Raise error
         return E_MEMORY_ERROR::EC_SizeMismatch;
 }
Allocator Allocator::operator= (Allocator const &) private
void Allocator::OutputMemoryInfo ()
Called only in the destructor, but available for calling manually if desired; will always output the memory stats for the application run, but will also write out the information on any unfreed memory.
Outputs to MEM_LEAK_LOG_NAME, but if it's not writable, it is printed to stderr instead.
Todo:
causes warning 'cast to pointer from integer of different size'
Definition at line 167 of file Allocator.cc.
References _allocs, _current_allocated, _frees, _memblocks, _total_allocated, block_offset_realmem, CheckBlock(), EC_CorruptFooter, EC_CorruptHeader, EC_NoMemoryBlock, EC_SizeMismatch, HEADER_FOOTER_SIZE, MEM_LEAK_LOG_NAME, MEM_OUTPUT_LIMIT, and PRINT_POINTER.
Referenced by ~Allocator().
 {
         FILE*           leak_file;
         bool            close_file = true;
         uint32_t        i = 0;
         E_MEMORY_ERROR  result;
         // we don't store/track the user-requested amounts, only the real
         uint32_t        requested_alloc;
         uint32_t        requested_unfreed;
         /* since Windows has been kind enough to not provide more standards
          * complaint security functionality, we shall have to use their own
          * fopen_s. POSIX builds can happily use the 'x' flag to provide a
          * decent security level - fopen_s is still vulnerable to potential
          * exploits ironically... */
 #if defined(_WIN32)
         if ( fopen_s(&leak_file, MEM_LEAK_LOG_NAME, "w+") != 0 )
         {
 #else
         if (( leak_file = fopen(MEM_LEAK_LOG_NAME, "w+")) == nullptr )
         {
 #endif
                 leak_file = stdout;
                 close_file = false;
         }
         /* Remove memory block sizes, multiplied by the number of allocations,
          * which is taken away from the total amount allocated. */
         requested_alloc         = _total_allocated - (HEADER_FOOTER_SIZE * _allocs);
         /* Remove memory block sizes, multiplied by the number of pending frees,
          * which is to be taken away from the current amount still allocated. */
         requested_unfreed       = _current_allocated - (HEADER_FOOTER_SIZE * (_allocs - _frees));
         fprintf(leak_file,
                 "# Details\n"
                 "Header+Footer Size......: %lu\n"
                 "\n"
                 "# Code Stats\n"
                 "Allocations.............: %u\n"
                 "Frees...................: %u\n"
                 "Pending Frees...........: %u\n"
                 "\n"
                 "# Totals, Real\n"
                 "Bytes Allocated.........: %u\n"
                 "Unfreed Bytes...........: %u\n"
                 "\n"
                 "# Totals, Requested\n"
                 "Bytes Allocated.........: %u\n"
                 "Unfreed Bytes...........: %u\n"
                 "\n"
                 "##################\n"
                 "  Unfreed Blocks  \n",
                 HEADER_FOOTER_SIZE,
                 _allocs, _frees, (_allocs - _frees),
                 _total_allocated, _current_allocated,
                 requested_alloc, requested_unfreed
                 );
         for ( auto block_ptr : _memblocks )
         {
                 i++;
                 fprintf(leak_file,
                         "##################\n"
                         "%u)\n"
                         "Block...: " PRINT_POINTER
                         "\n",
                         i, (uintptr_t)block_ptr
                 );
                 result = CheckBlock(block_ptr);
                 switch ( result )
                 {
                 case E_MEMORY_ERROR::EC_NoMemoryBlock:
{
                                 fprintf(leak_file,
                                         "Error...: Block Pointer was NULL\n"
                                 );
                                 break;
                         }
                 case E_MEMORY_ERROR::EC_CorruptFooter:
{
                                 fprintf(leak_file,
                                         "Error...: Corrupt Footer\n"
                                 );
                                 break;
                         }
                 case E_MEMORY_ERROR::EC_CorruptHeader:
{
                                 fprintf(leak_file,
                                         "Error...: Corrupt Header\n"
                                 );
                                 break;
                         }
                 case E_MEMORY_ERROR::EC_SizeMismatch:
{
                                 fprintf(leak_file,
                                         "Error...: Size Mismatch (%u actual bytes)\n",
                                         block_ptr->requested_size
                                 );
                                 break;
                         }
                 default:
                         break;
                 }
                 /* can't fall through in switch, so have to do a secondary check
                  * as we can't print data that's corrupt or a nullptr */
                 if ( result != EC_NoMemoryBlock && result != EC_CorruptHeader )
                 {
                         fprintf(leak_file,
                                 "Size....: %u\n"
                                 "Function: %s\n"
                                 "File....: %s\n"
                                 "Line....: %u\n"
                                 "Owner...: %p\n",
                                 block_ptr->requested_size,
                                 block_ptr->function,
                                 block_ptr->file,
                                 block_ptr->line,
                                 block_ptr->owner
                         );
                         fprintf(leak_file, "Data....: ");
                         for ( uint32_t j = 0;
                                 j < block_ptr->requested_size && j < MEM_OUTPUT_LIMIT;
                                 j++ )
{
                                 fprintf(leak_file,
                                         "%02x ",
                                         block_offset_realmem(block_ptr)[j]);
                         }
                         fprintf(leak_file, "\n");
                 }
         }
         if ( close_file )
                 fclose(leak_file);
         /* try to free whatever we didn't during runtime; if any of these are
          * screwed (heap corruption) then this will probably trigger a crash */
         while ( _memblocks.size() > 0 )
         {
                 free(_memblocks.back());
                 _memblocks.pop_back();
         }
 }
void * Allocator::TrackedAlloc (const uint32_t num_bytes, const char * file, const char * function, const uint32_t line, const Object * owner = nullptr)
Tracked version of malloc - use the MALLOC macro to call this, as it will setup the parameters for you, barring the num_bytes.
This function will dynamically alter the requested amount in order to leave space for a header and footer; the client code does not need to handle, or be aware, of this fact.
Parameters
[in] num_bytes The number of bytes to allocate
[in] file The file this method was called in
[in] function The function this method was called in
[in] line The line number in the file this method was called in
[in] owner (Optional) The owner of the memory block
Returns
A pointer to the allocated memory, or a nullptr if the allocation failed.
Definition at line 319 of file Allocator.cc.
References _allocs, _current_allocated, _memblocks, _mutex, _total_allocated, block_offset_footer, block_offset_realmem, memblock_header::file, memblock_header::footer, memblock_header::function, HEADER_FOOTER_SIZE, memblock_header::line, memblock_footer::magic, memblock_header::magic, mem_footer_magic, mem_header_magic, MEM_ON_INIT, memblock_header::owner, PATH_CHAR, memblock_header::real_size, and memblock_header::requested_size.
Referenced by TrackedRealloc().
 {
         memblock_header*        mem_block = nullptr;
         memblock_footer*        mem_footer = nullptr;
         void*                   mem_return = nullptr;
         uint32_t                patched_alloc = 0;      // num_bytes + memblocks
         // allocate the requested amount, plus the size of the header & footer memblocks
         patched_alloc = num_bytes + HEADER_FOOTER_SIZE;
         // the actual, real, physical allocation of memory
         mem_block = (memblock_header*)malloc(patched_alloc);
         if ( mem_block == nullptr )
                 goto alloc_failure;
         // initialize the value for the new memory
         memset(mem_block, MEM_ON_INIT, patched_alloc);
 #if defined(_WIN32)
 #       define PATH_CHAR        '\\'
 #else
 #       define PATH_CHAR        '/'
 #endif
         // we don't want the full path information that compilers set
         if (( file = strrchr(file, PATH_CHAR)) != nullptr )
                 file++;
         // calculate the offsets of the return memory and the footer
         mem_return = block_offset_realmem(mem_block);
         mem_footer = block_offset_footer(mem_block, num_bytes);
         // prepare the structure internals
         mem_footer->magic       = mem_footer_magic;
         mem_block->footer       = mem_footer;
         mem_block->magic        = mem_header_magic;
         mem_block->owner        = owner;
         mem_block->line         = line;
         mem_block->real_size            = patched_alloc;
         mem_block->requested_size       = num_bytes;
         /* you should be using strlcpy if you're doing character buffer copying
          * and other functionality!! For the sake of securing your application,
          * please USE IT!
          * We provide a 'normal, well-known' alternative for the sake of the
          * example using strncpy (which is in standard headers everywhere) */
 #if defined(HAVE_STRLCPY)
         strlcpy(mem_block->file, file, sizeof(mem_block->file));
         strlcpy(mem_block->function, function, sizeof(mem_block->function));
 #else
         strncpy(mem_block->file, file, sizeof(mem_block->file)-1);
         strncpy(mem_block->function, function, sizeof(mem_block->function)-1);
 #endif
         /* lock this class, only 1 thread to update sensitive internals at a
          * time - lock for as little time as possible! */
         _mutex.lock();
         // update the stats, using patched values
         _allocs++;
         _current_allocated += patched_alloc;
         _total_allocated += patched_alloc;
         // append it to the vector
         _memblocks.push_back(mem_block);
         // unlock the allocator, other threads can now allocate from this class
         _mutex.unlock();
         return mem_return;
 alloc_failure:
         return nullptr;
 }
void Allocator::TrackedFree (void * memory)
Tracked version of free - use the FREE macro to call this, for consistency and potential future changes.
In compliance with the C standard, if memory is a nullptr, this function performs no action. No action is also performed if a memory validation check fails (i.e. the supplied block is corrupt or otherwise invalid), as doing so could crash the application, and miss logging the information.
Parameters
[in] memory A pointer to the memory previously allocated by TrackedAlloc (which should be called via MALLOC)
Definition at line 402 of file Allocator.cc.
References _current_allocated, _frees, _memblocks, _mutex, block_offset_header, memblock_header::file, memblock_header::line, MEM_AFTER_FREE, memblock_header::real_size, memblock_header::requested_size, and ValidateMemory().
Referenced by TrackedRealloc().
 {
         memblock_header*        mem_block = nullptr;
         // as per the C standard, if it's a nullptr, do nothing
         if ( memory == nullptr )
                 return;
         if ( !ValidateMemory(memory) )
                 return;
         mem_block = block_offset_header(memory);
 #if !defined(DISABLE_MEMORY_OP_TO_STDOUT)
         printf( "free [%s (%u bytes) line %u]\n"
                 "\tBlock: %p | Usable Block: %p\n",
                 mem_block->file, mem_block->requested_size, mem_block->line,
                 mem_block, memory);
 #endif
         // stop other class modifications
         _mutex.lock();
         // remove the mem_block from the vector
         _memblocks.erase(std::find(_memblocks.begin(), _memblocks.end(), mem_block));
         // update the context stats
         _frees++;
         _current_allocated -= (mem_block->real_size);
         // we're done with the class internals, open it up again
         _mutex.unlock();
         // fill the app-allocated memory (highlights use after free)
         memset(mem_block, MEM_AFTER_FREE, mem_block->real_size);
         // perform the actual freeing of memory, including our header + footer
         free(mem_block);
         return;
 }
void * Allocator::TrackedRealloc (void * memory_block, const uint32_t num_bytes, const char * file, const char * function, const uint32_t line, const Object * owner = nullptr)
Tracked version of realloc - use the REALLOC macro to call this.
In compliance with the C standard, if memory_block is a nullptr, the end result is the same as calling TrackedAlloc (i.e. malloc). The same applies if num_bytes is 0 - TrackedFree (i.e. free) will be called on the memory_block.
No validation is performed on the original block of memory, and unlike the real realloc, we call TrackedAlloc regardless of size differences and other parameters. The previous memory is then moved into this newly allocated block, and the original freed.
As a result, a TrackedRealloc guarantees that the returned pointer will never be the same as the one passed in.
Parameters
[in] memory_block The pointer to memory returned by TrackedAlloc()
[in] num_bytes The new number of bytes to allocate
[in] file The file this method was called in
[in] function The function this method was called in
[in] line The line number in the file this method was called in
[in] owner (Optional) The owner of the memory block
Return values
nullptr if the function fails due to invalid parameters, or the call to realloc fails
Returns
A pointer to the usable block of memory allocated
Definition at line 447 of file Allocator.cc.
References _mutex, block_offset_header, memblock_header::requested_size, TrackedAlloc(), and TrackedFree().
 {
         memblock_header*        mem_block = nullptr;
         void*                   mem_return = nullptr;
         if ( memory_block == nullptr )
         {
                 // if real_mem is NULL, call malloc [ISO C]
                 return TrackedAlloc(new_num_bytes, file, function, line, owner);
         }
         if ( new_num_bytes == 0 )
         {
                 // if new_num_bytes is 0 & real_mem is not null, call free [ISO C]
                 TrackedFree(memory_block);
                 /* whether it works or fails, the memory is still unusable, so
                  * return a nullptr */
                 return nullptr;
         }
         _mutex.lock();
 #if !defined(DISABLE_MEMORY_OP_TO_STDOUT)
         // since we call track_alloc, make the log info accurate
         printf( "realloc [%s (%u bytes) line %u]\n"
                 "\tTo be allocated in the following malloc; using memory block: %p\n",
                 file, new_num_bytes, line,
                 memory_block);
 #endif
         mem_return = (void*)TrackedAlloc(new_num_bytes, file, function, line, owner);
         if ( mem_return != nullptr )
         {
                 mem_block = block_offset_header(memory_block);
                 // move the original data into the new allocation
                 mem_block->requested_size < new_num_bytes ?
                         memmove(mem_return, memory_block, new_num_bytes) :
                         memmove(mem_return, memory_block, mem_block->requested_size);
                 // free the original block
                 TrackedFree(memory_block);
         }
         _mutex.unlock();
         return mem_return;
 }
bool Allocator::ValidateMemory (void * memory) const private
Validates a block of memory; if no block is supplied, and nullptr is passed in, every tracked block currently present is validated.
If present, the block passed in must be at the header, and NOT the pointer returned to the of the TrackedAlloc/TrackedRealloc caller.
Internally calls CheckBlock().
Parameters
[in] memory A pointer to the block of memory to validate
Return values
true if the memory is not corrupt and usable
false if the memory failed one of the checks
Definition at line 507 of file Allocator.cc.
References _memblocks, _mutex, block_offset_header, CheckBlock(), and EC_NoError.
Referenced by TrackedFree().
 {
         bool    ret = true;
         _mutex.lock();
         // if no block was specified, check the entire list
         if ( memory == nullptr )
         {
                 for ( auto block : _memblocks )
                 {
                         // bail if a block is invalid
                         if ( CheckBlock(block) != E_MEMORY_ERROR::EC_NoError )
{
                                 ret = false;
                                 break;
                         }
                 }
         }
         else
         {
                 memblock_header*        mem_block = block_offset_header(memory);
                 ret = (CheckBlock(mem_block) == E_MEMORY_ERROR::EC_NoError);
         }
         _mutex.unlock();
         return ret;
 }
Friends And Related Function Documentation
friend class Runtime friend
Definition at line 148 of file Allocator.h.
Member Data Documentation
uint32_t Allocator::_allocs private
The amount of times new has been called successfully
Definition at line 158 of file Allocator.h.
Referenced by OutputMemoryInfo(), and TrackedAlloc().
uint32_t Allocator::_current_allocated private
Currently allocated amount of bytes
Definition at line 160 of file Allocator.h.
Referenced by OutputMemoryInfo(), TrackedAlloc(), and TrackedFree().
uint32_t Allocator::_frees private
The amount of times delete has been called successfully
Definition at line 159 of file Allocator.h.
Referenced by OutputMemoryInfo(), and TrackedFree().
std::vector<memblock_header*> Allocator::_memblocks private
Performance benchmarks have shown that a vector is fastest when the size of the element is known, for insert, remove, and search! http://www.baptiste-wicht.com/2012/12/cpp-benchmark-vector-list-deque/
The small data type (a pointer) is most beneficial here.
Definition at line 176 of file Allocator.h.
Referenced by Allocator(), OutputMemoryInfo(), TrackedAlloc(), TrackedFree(), ValidateMemory(), and ~Allocator().
std::recursive_mutex Allocator::_mutex mutable private
The lock for making modifications to _memblocks. Mutable to allow constness for retrieval functions, recursive for multi-locking.
Definition at line 167 of file Allocator.h.
Referenced by TrackedAlloc(), TrackedFree(), TrackedRealloc(), and ValidateMemory().
uint32_t Allocator::_total_allocated private
The total amount of allocated bytes
Definition at line 161 of file Allocator.h.
Referenced by OutputMemoryInfo(), and TrackedAlloc().